version: "3.9"

services:
  mysqldb:
    image: mysql:latest
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s
      retries: 10
    restart: on-failure

    environment:
      - MYSQL_DATABASE=batch
      - MYSQL_ROOT_PASSWORD=root
  app:
    build: .
    ports:
      - 8081:8081
    environment:
      - MYSQL_URL=mysqldb

    depends_on:
      mysqldb:
        condition: service_healthy
